export const wordpuzzlehint = {
  Apple: "A popular fruit with a crunchy texture.",
  Banana: "A yellow fruit that is often curved.",
  Cherry: "A small, round, red fruit that grows on trees.",
  Grape: "A small, sweet fruit that can be green or purple.",
  Orange: "A citrus fruit with a bright orange color.",
  Dog: "A common pet known for its loyalty.",
  Cat: "A furry animal often kept as a pet.",
  House: "A place where people live.",
  Car: "A mode of transportation with four wheels.",
  Sun: "The bright, shining star in our solar system.",
  Moon: "Earth's natural satellite.",
  Tree: "A tall, woody plant with branches and leaves.",
  Bird: "Feathered creatures that can fly.",
  Book: "A collection of written or printed pages.",
  Chair: "A piece of furniture for sitting.",
  Table: "A flat surface for placing objects.",
  Flower: "A colorful bloom from a plant.",
  Ocean: "A vast body of saltwater.",
  Smile: "A facial expression that shows happiness.",
  Laugh: "The sound made when someone finds something funny.",
  Run: "To move quickly on foot.",
  Jump: "Springing into the air with both feet.",
  Fish: "Water-dwelling animals with scales.",
  Cake: "A sweet baked dessert.",
  Hat: "A head-covering accessory.",
  Shirt: "A garment worn on the upper body.",
  Pants: "Clothing for the lower part of the body.",
  Music: "Sounds arranged in a harmonious way.",
  Rain: "Water falling from the sky.",
  Snow: "Frozen precipitation in the form of white flakes.",
  Star: "A distant celestial object in the night sky.",
  Pen: "A writing instrument.",
  Pencil: "A writing tool with a graphite core.",
  Ball: "A round object used in various sports.",
  Game: "An activity for fun and entertainment.",
  Watch: "A timekeeping device worn on the wrist.",
  Clock: "A device used to tell time.",
  Ship: "A vessel that travels on water.",
  Beach: "Sandy shore by the sea.",
  Moon: "Earth's natural satellite.",
  Key: "A small metal tool for unlocking things.",
  Door: "An entryway into a building.",
  Window: "An opening in a wall with glass.",
  Cake: "A sweet baked dessert.",
  Juice: "A drink made from pressed fruits.",
  Train: "A long vehicle that runs on tracks.",
  Apple: "A popular fruit with a crunchy texture.",
  Bike: "A two-wheeled human-powered vehicle.",
  Ring: "A circular piece of jewelry worn on fingers.",
  Rope: "A strong, thick cord made of twisted fibers."
};
export const words = [
  "Apple",
  "Banana",
  "Cherry",
  "Grape",
  "Orange",
  "Dog",
  "Cat",
  "House",
  "Car",
  "Sun",
  "Moon",
  "Tree",
  "Bird",
  "Book",
  "Chair",
  "Table",
  "Flower",
  "Ocean",
  "Smile",
  "Laugh",
  "Run",
  "Jump",
  "Fish",
  "Cake",
  "Hat",
  "Shirt",
  "Pants",
  "Music",
  "Rain",
  "Snow",
  "Star",
  "Pen",
  "Pencil",
  "Ball",
  "Game",
  "Watch",
  "Clock",
  "Ship",
  "Beach",
  "Moon",
  "Key",
  "Door",
  "Window",
  "Cake",
  "Juice",
  "Train",
  "Apple",
  "Bike",
  "Ring",
  "Rope"
];

export const wordLists = {
  1: ["Apple", "Banana", "Cherry", "Grape", "Orange"],
  2: ["Strawberry", "Lemon", "Peach", "Watermelon", "Pineapple"],
  3: ["Mango", "Kiwi", "Pear", "Blueberry", "Raspberry"],
  4: ["Dog", "Cat", "Elephant", "Lion", "Horse"],
  5: ["Tiger", "Monkey", "Giraffe", "Kangaroo", "Zebra"],
  6: ["Red", "Green", "Blue", "Yellow", "Purple"],
  7: ["Orange", "Pink", "Brown", "Black", "White"],
  8: ["Car", "Bicycle", "Bus", "Train", "Boat"],
  9: ["Helicopter", "Motorcycle", "Scooter", "Truck", "Aeroplane"],
  10: ["One", "Four", "Three", "Five", "Two"],
  11: ["Six", "Seven", "Eight", "Nine", "Ten"],
  12: ["Circle", "Square", "Triangle", "Rectangle", "Oval"],
  13: ["Diamond", "Heart", "Star", "Crescent", "Hexagon"],
  14: ["Pizza", "Burger", "Pasta", "Salad", "Sushi"],
  15: ["Pancake", "Ice Cream", "Sandwich", "Cake", "Spaghetti"]
};
